#pragma once

#include <QtGlobal>

#if defined(OPTIMIZATIONSTESTER_LIBRARY)
#  define OPTIMIZATIONSTESTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define OPTIMIZATIONSTESTERSHARED_EXPORT Q_DECL_IMPORT
#endif
